id: I68E8BC8A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T22:45:48+00:00'
last_modified: '2022-06-07T12:41:29.938920+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20620
  title: གངས་ཅན་ལྗོངས་སུ་འཁྲུངས་པའི་རྒྱུན་སྤྱོད་བོད་སྨན་སྐྱེས་དངོས་སྨན་རྫས་བཏུ་ཐབས་ཀྱི་ལག་དེབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E3FF:
      image_group_id: I8LS20622
      title: ''
      total_pages: 55
      order: 1
      base_file: E3FF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
